/*
 */

/* ----------------------------------------------------------------------
 * modSequencer Module
 * ----------------------------------------------------------------------
 * Description:
 *   
 * Basically a bunch of Push/Pops.  A true hack but sometimes Express
 * requires a bit of man-handling.   I shamelessly use this on occasion.
 *
 * Authors: 
 *   Brian Selle, Leon Thrane, Advanced Visual Systems Inc.
 *   Documentation written by Ian Curington
 *
 * Revision: 8th February 2000 - Paul G. Lever, IAC
 *   Converted to IAC format.
 *
 * ----------------------------------------------------------------------
 * Note:
 *   The gen.h include file is generated by Express when the module is 
 *   compiled. It avoids including "user.h" or "express.h" directly, so 
 *   that the module may be moved across the processes by changing the V
 *   properties in the library.
 * ----------------------------------------------------------------------
 */

#include "xp_comm_proj/sequencr/gen.h"
#include "XP_OM_CALL.h"

int
Sequencer_modSequencer::update(OMevent_mask , int)
{
   this->push_ctx();
     seq_1 = 1;
   this->pop_ctx();     

   this->push_ctx();
     seq_2 = 1;
   this->pop_ctx();     

   this->push_ctx();
     seq_3 = 1;
   this->pop_ctx();     

   // Successful return
   return( XP_SUCCESS );
}

/* end of file */
