//
//standard placement of View - you may edit ViewUI.Shell dimensions to square
//or whatever shape you want
//

// you might want to change this for Screen resolution (1024 x 780 or 1280 x 1024)

//   Applications.ModuleStack.sligview.Scene.View.ViewUI.ViewPanel.UI.panel.UIshell<NEx=650.,NEy=480.> 
    Applications.ModuleStack.Viewer3D.ViewUI.Shell<NEx=650.,NEy=480.> 
 {
$push
x=340;
y=0;
width=680;
height=955;
title=>" - ASSIST 1.4  ";
$pop
  };
Applications.assist0.assist1.RESET_VIEW_button.visible=0;
Applications.assist0.assist1.RED_VIEW_button.visible=1;


