/*
 */

/* ----------------------------------------------------------------------
 * CFDValsNodeData Module
 * ----------------------------------------------------------------------
 * Description:
 *   
 * CFD Values Module, transforms node data from input to output,
 * applying 7 derived value functions.
 * The input is assumed to be 5-component PLOT3D format
 *
 * Author: Ian Curington, March 3, 1997
 *
 * Revision: 
 *    4 March 97 Ian Curington: V3.1 on W95 port testing
 *   12 March 97 Ian Curington: min-max locally, fewer OM calls
 *                              new mem alloc scheme for output fields
 *    9 Feb   98 Paul G. Lever: added check to see if input is valid
 *
 * ----------------------------------------------------------------------
 * Note:
 *   The gen.h include file is generated by Express when the module is 
 *   compiled. It avoids including "user.h" or "express.h" directly, so 
 *   that the module may be moved across the processes by changing the V
 *   properties in the library.
 * ----------------------------------------------------------------------
 */

#include "xp_comm_proj/cfdvals/gen.h"

/* to enable debug message, please uncomment the following symbol: */

/* #define DEBUG_PRINT 1 */

/*
 ***** MACROS *****
 */

/*
 * Error path: use ERRerror instead of printf,
 * since it reports nested context in messages
 */

#define CFD_ERROR(MESS) {ERRerror("CFD Values",1,ERR_ORIG,MESS);return 0;}
#define SILENT_RTN(MESS) { return 0; }

#define MAX_BLOCKS 200

#define CFD_MAXFLOAT ((float)3.0e+30)

static compute_energy( float *, float *, float *, int );
static compute_mom_squared( float *, float *, float *, float *, int );
static compute_press( float *, float *, float *, float *, float *, float *, int, double );
static compute_enthalpy( float *, float *, float *, float *, float *, float *, int, double );
static compute_mach( float *, float *, float *, float *, float *, float *, int, double );
static compute_temp( float *, float *, float *, float *, float *, float *, int, double, double );
static compute_tot_press( float *, float *, float *, float *, float *, float *, int, double );
static compute_tot_temp( float *, float *, float *, float *, float *, float *, int, double, double );
static scan_minmax_range ( float *, int, float *, float *, int );

/*********************************
 * Express Module Entry Point    *
 *********************************/

int
cfd_values_update(OMobj_id cfd_vals_id, OMevent_mask event_mask, int seq_num)
{
   /***********************/
   /*  Declare variables  */
   /***********************/

   OMobj_id     in_id, in_fields[MAX_BLOCKS];
   int          in_ncomp, in_comp_count, in_veclen;
   int          out_ncomp, out_comp_count, out_veclen;
   int          in_data_type, in_ndata;
   float        *dens, *xmom, *ymom, *zmom, *stag;
   OMobj_id     out_id, out_fields[MAX_BLOCKS];
   float        *out_data;
   double       gamma;
   double       gas_constant;
   int		do_energy, do_pres, do_enthalpy, do_mach, do_temp, do_totpres, do_tottemp;
   int          nnodes, nblocks, nbndims, nbdims[20];
   int          i,j,m;
   int          interrupt;
   float        min, max, rmin[50], rmax[50];
   
   int status;
   
   OMstatus_check(1,"cfd values started",&interrupt);
   /***********************/
   /*  Get input values   */
   /***********************/

   /* Get gamma's value */
   if (OMget_name_real_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("gamma"), /* name of param */
			   &gamma) != 1)           /* return value */
      CFD_ERROR("Could not get gamma value.");

   /* Get gas_constant's value */
   if (OMget_name_real_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("gas_constant"), /* name of param */
			   &gas_constant) != 1)           /* return value */
      CFD_ERROR("Could not get gas_constant value.");

   /* Get do_energy's value */
   if (OMget_name_int_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("do_energy"), /* name of param */
			   &do_energy) != 1)           /* return value */
      CFD_ERROR("Could not get do_energy value.");

   /* Get do_pres's value */
   if (OMget_name_int_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("do_pres"), /* name of param */
			   &do_pres) != 1)           /* return value */
      CFD_ERROR("Could not get do_pres value.");

   /* Get do_enthalpy's value */
   if (OMget_name_int_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("do_enthalpy"), /* name of param */
			   &do_enthalpy) != 1)           /* return value */
      CFD_ERROR("Could not get do_enthalpy value.");

   /* Get do_mach's value */
   if (OMget_name_int_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("do_mach"), /* name of param */
			   &do_mach) != 1)           /* return value */
      CFD_ERROR("Could not get do_mach value.");

   /* Get do_temp's value */
   if (OMget_name_int_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("do_temp"), /* name of param */
			   &do_temp) != 1)           /* return value */
      CFD_ERROR("Could not get do_temp value.");

   /* Get do_totpres's value */
   if (OMget_name_int_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("do_totpres"), /* name of param */
			   &do_totpres) != 1)           /* return value */
      CFD_ERROR("Could not get do_totpres value.");

   /* Get do_tottemp's value */
   if (OMget_name_int_val(cfd_vals_id,     /* id of whole module */
			   OMstr_to_name("do_tottemp"), /* name of param */
			   &do_tottemp) != 1)           /* return value */
      CFD_ERROR("Could not get do_tottemp value.");

   /* Set number of node data components based on boolean buttons */
   out_ncomp = do_energy + do_pres + do_enthalpy + do_mach + do_temp + do_totpres + do_tottemp;
   if ( out_ncomp <= 0 ) SILENT_RTN("no components selected");
   if ( out_ncomp > 7 ) CFD_ERROR("something wrong with boolean input params");
    

   /* Get the field id's so we can access the fields */
   /* Get field id */
   in_id= OMfind_subobj(cfd_vals_id, OMstr_to_name("in"), OM_OBJ_RD);

   /* Get field id */
   out_id= OMfind_subobj(cfd_vals_id, OMstr_to_name("out"), OM_OBJ_RW);

   status = OMget_array_dims( in_id, &nbndims, nbdims );
   
   if( status != 1 ) return 1;
   
   if ( nbndims <= 0 )
      CFD_ERROR("input multiblock list empty");
   if ( nbndims >= 2 )
      CFD_ERROR("input multiblock list has too many dimensions");
   if ( nbdims[0] <= 0 )
      CFD_ERROR("input multiblock list empty");
   nblocks = nbdims[0];

   OMget_array_dims( out_id, &nbndims, nbdims );
   if ( nbndims <= 0 )
      CFD_ERROR("output multiblock list empty");
   if ( nbndims >= 2 )
      CFD_ERROR("output multiblock list has too many dimensions");
   if ( nbdims[0] <= 0 )
      CFD_ERROR("output multiblock list empty");

   /*
    * establish id's for each block in both input and ouput
    */
   for (i=0; i< nblocks; i++) 
   {
		if ((OMget_array_val(in_id, i, in_fields+i, OM_OBJ_RD)) != 1)
		    CFD_ERROR("could not obtain obj id of sub-field in input mblock");
		if ((OMget_array_val(out_id, i, out_fields+i, OM_OBJ_RD)) != 1)
		    CFD_ERROR("could not obtain obj id of sub-field in output mblock");
   }
   OMstatus_check(5,"cfd values params resolve",&interrupt);

   /*
    * Loop over all Fields in Multi-Block Structure
    */
   for (j=0; j< nblocks; j++) 
   {
       OMstatus_check(10+((j*80)/nblocks),"cfd values processing",&interrupt);

       in_id = in_fields[j];
       out_id = out_fields[j];

       /* copy over the number of nodes */
       if (FLDget_nnodes (in_id, &nnodes) != 1) 
              CFD_ERROR("error setting output nnodes");
       if (FLDset_nnodes (out_id, nnodes) != 1) 
              CFD_ERROR("error setting output nnodes");

       /* Get number of node data components */
       FLDget_node_data_ncomp (in_id, &in_ncomp);
       if ( in_ncomp != 5 ) CFD_ERROR("expected 5 float components on input");
    
       FLDset_node_data_ncomp (out_id, out_ncomp);
    
    
       /* check veclen input for sanity */
       for (in_comp_count=0; in_comp_count < in_ncomp; in_comp_count++) {
          FLDget_node_data_veclen (in_id, in_comp_count, &in_veclen);
          if ( in_veclen != 1 )
              CFD_ERROR("expected input veclen of each component to be =1");
       }
    
       /*
        * get the input field values prior to computation
        */
    
        /* Density */
        if (FLDget_node_data (in_id, 0, &in_data_type, &dens, &in_ndata, OM_GET_ARRAY_RD) != 1)
    	CFD_ERROR("Could not get input density field node data.");
    
        if ( in_ndata != nnodes )
    	CFD_ERROR("problem with number of nodes not matching on two calls");

        /* X momentum */
        if (FLDget_node_data (in_id, 1, &in_data_type, &xmom, &in_ndata, OM_GET_ARRAY_RD) != 1)
    	CFD_ERROR("Could not get input xmom field node data.");
    
        /* Y momentum */
        if (FLDget_node_data (in_id, 2, &in_data_type, &ymom, &in_ndata, OM_GET_ARRAY_RD) != 1)
    	CFD_ERROR("Could not get input ymom field node data.");
    
        /* Z momentum */
        if (FLDget_node_data (in_id, 3, &in_data_type, &zmom, &in_ndata, OM_GET_ARRAY_RD) != 1)
    	CFD_ERROR("Could not get input zmom field node data.");
    
        /* Stagnation */
        if (FLDget_node_data (in_id, 4, &in_data_type, &stag, &in_ndata, OM_GET_ARRAY_RD) != 1)
    	CFD_ERROR("Could not get input stagnation field node data.");
    
	/*
	 * Set up temporary buffer to calculate derived quantities
	 * try using ARR instead of malloc because it has more instrumentation
	 * this is a relatively small buffer that is used over and over.
	 */
        if ((out_data= (float *)ARRalloc(NULL, DTYPE_FLOAT, in_ndata, NULL)) == NULL)
    	     CFD_ERROR("Could not allocate temp buffer memory for output array.");


#ifdef DEBUG_PRINT
printf("density    %f %f %f %f\n",dens[0],dens[1],dens[2],dens[3]);
printf("x momentum %f %f %f %f\n",xmom[0],xmom[1],xmom[2],xmom[3]);
printf("y momentum %f %f %f %f\n",ymom[0],ymom[1],ymom[2],ymom[3]);
printf("z momentum %f %f %f %f\n",zmom[0],zmom[1],zmom[2],zmom[3]);
#endif
        out_comp_count = 0;  /* which component */
    
        /*************************
         * energy                *
         *************************/
        if ( do_energy )
        {
          /* compute derived quantity */
          compute_energy   (dens, stag, out_data, nnodes);

#ifdef DEBUG_PRINT
printf("energy     %f %f %f %f\n",out_data[0],out_data[1],out_data[2],out_data[3]);
#endif
    
          scan_minmax_range ( out_data, nnodes, &(rmin[out_comp_count]), &(rmax[out_comp_count]),j);
    
          if (FLDset_node_data_comp (out_id, out_comp_count, 1, "energy", "joules") != 1)
    					CFD_ERROR("error setting node data component and labels");
          if (FLDset_node_data (out_id, out_comp_count,out_data,DTYPE_FLOAT,
                                   in_ndata,OM_SET_ARRAY_COPY)!= 1)
    	                                CFD_ERROR("Could not set output CFD values node data.");
          out_comp_count++;
        }

        /*************************
         * pressure              *
         *************************/
        if ( do_pres )
        {
          /* compute derived quantity */
          compute_press(dens, xmom, ymom, zmom, stag, out_data, nnodes, gamma);

#ifdef DEBUG_PRINT
printf("pressure     %f %f %f %f\n",out_data[0],out_data[1],out_data[2],out_data[3]);
#endif
    
          scan_minmax_range ( out_data, nnodes, &(rmin[out_comp_count]), &(rmax[out_comp_count]),j );
    
          if (FLDset_node_data_comp (out_id, out_comp_count, 1, "pressure", "pres units") != 1)
    					CFD_ERROR("error setting node data component and labels");
          if (FLDset_node_data (out_id, out_comp_count,out_data,DTYPE_FLOAT,
                                   in_ndata,OM_SET_ARRAY_COPY)!= 1)
    	                                CFD_ERROR("Could not set output CFD values node data.");
          out_comp_count++;
        }
    
    
        /*************************
         * enthalpy              *
         *************************/
        if ( do_enthalpy )
        {
          /* compute derived quantity */
          compute_enthalpy (dens, xmom, ymom, zmom, stag, out_data, nnodes, gamma);
#ifdef DEBUG_PRINT
printf("enthalpy     %f %f %f %f\n",out_data[0],out_data[1],out_data[2],out_data[3]);
#endif
    
          scan_minmax_range ( out_data, nnodes, &(rmin[out_comp_count]), &(rmax[out_comp_count]),j );

          if (FLDset_node_data_comp (out_id, out_comp_count, 1, "enthalpy", "units") != 1)
    					CFD_ERROR("error setting node data component and labels");
          if (FLDset_node_data (out_id, out_comp_count,out_data,DTYPE_FLOAT,
                                   in_ndata,OM_SET_ARRAY_COPY)!= 1)
    	                                CFD_ERROR("Could not set output CFD values node data.");
          out_comp_count++;
        }
    
        /*************************
         * mach number           *
         *************************/
        if ( do_mach )
        {
          /* compute derived quantity */
          compute_mach     (dens, xmom, ymom, zmom, stag, out_data, nnodes, gamma);
#ifdef DEBUG_PRINT
printf("mach number     %f %f %f %f\n",out_data[0],out_data[1],out_data[2],out_data[3]);
#endif

          scan_minmax_range ( out_data, nnodes, &(rmin[out_comp_count]), &(rmax[out_comp_count]),j );
    
          if (FLDset_node_data_comp (out_id, out_comp_count, 1, "mach number", "speed") != 1)
    					CFD_ERROR("error setting node data component and labels");
          if (FLDset_node_data (out_id, out_comp_count,out_data,DTYPE_FLOAT,
                                   in_ndata,OM_SET_ARRAY_COPY)!= 1)
    	                                CFD_ERROR("Could not set output CFD values node data.");
          out_comp_count++;
        }
    
        /*************************
         * local temperature     *
         *************************/
        if ( do_temp )
        {
          /* compute derived quantity */
          compute_temp     (dens, xmom, ymom, zmom, stag, out_data, nnodes, gamma, gas_constant);
#ifdef DEBUG_PRINT
printf("local temp     %f %f %f %f\n",out_data[0],out_data[1],out_data[2],out_data[3]);
#endif

          scan_minmax_range ( out_data, nnodes, &(rmin[out_comp_count]), &(rmax[out_comp_count]),j );
    
          if (FLDset_node_data_comp (out_id, out_comp_count, 1, "temperature", "celsius") != 1)
    					CFD_ERROR("error setting node data component and labels");
          if (FLDset_node_data (out_id, out_comp_count,out_data,DTYPE_FLOAT,
                                   in_ndata,OM_SET_ARRAY_COPY)!= 1)
    	                                CFD_ERROR("Could not set output CFD values node data.");
          out_comp_count++;
        }
    
        /*************************
         * total pressure        *
         *************************/
        if ( do_totpres )
        {
          /* compute derived quantity */
          compute_tot_press(dens, xmom, ymom, zmom, stag, out_data, nnodes, gamma);
#ifdef DEBUG_PRINT
printf("total pressure     %f %f %f %f\n",out_data[0],out_data[1],out_data[2],out_data[3]);
#endif

          scan_minmax_range ( out_data, nnodes, &(rmin[out_comp_count]), &(rmax[out_comp_count]),j );
    
          if (FLDset_node_data_comp (out_id, out_comp_count, 1, "total pressure", "units") != 1)
    					CFD_ERROR("error setting node data component and labels");
          if (FLDset_node_data (out_id, out_comp_count,out_data,DTYPE_FLOAT,
                                   in_ndata,OM_SET_ARRAY_COPY)!= 1)
    	                                CFD_ERROR("Could not set output CFD values node data.");
          out_comp_count++;
        }
    
        /*************************
         * total temperature     *
         *************************/
        if ( do_tottemp )
        {
          /* compute derived quantity */
          compute_tot_temp (dens, xmom, ymom, zmom, stag, out_data, nnodes, gamma, gas_constant);

#ifdef DEBUG_PRINT
printf("total temperature     %f %f %f %f\n",out_data[0],out_data[1],out_data[2],out_data[3]);
#endif

          scan_minmax_range ( out_data, nnodes, &(rmin[out_comp_count]), &(rmax[out_comp_count]),j );
    
          if (FLDset_node_data_comp (out_id, out_comp_count, 1, "total temperature", "units") != 1)
    					CFD_ERROR("error setting node data component and labels");
          if (FLDset_node_data (out_id, out_comp_count,out_data,DTYPE_FLOAT,
                                   in_ndata,OM_SET_ARRAY_COPY)!= 1)
    	                                CFD_ERROR("Could not set output CFD values node data.");
          out_comp_count++;
        }


       /*  release our dependency on the input data pointer */
       /*  this should be done for each data component */
       ARRfree((char *)dens);
       ARRfree((char *)xmom);
       ARRfree((char *)ymom);
       ARRfree((char *)zmom);
       ARRfree((char *)stag);

       ARRfree((char *)out_data); /* local buffer */
       
   } /* end of multi-block loop */


   OMstatus_check(93,"cfd values min-max set",&interrupt);

   /*
    * Set the Min-Max ranges on all components of all blocks for consistancy
    */
   for ( j = 0; j < nblocks; j++ )	{
		if (FLDget_node_data_ncomp (out_fields[j], &out_ncomp) != 1) {
			CFD_ERROR("Error setting nnode_data");
		}
		for( m = 0; m < out_ncomp; m++ ) {
			if (FLDset_node_data_minmax(out_fields[j], m, 
					    (char *)&rmin[m], (char *)&rmax[m], DTYPE_FLOAT) != 1) {
				CFD_ERROR("Error setting minmax data");
			}
		}
   }
   OMstatus_check(99,"cfd values finished",&interrupt);

   /*
    * return to Object Manager with success flag
    */
   return(1);
}

/*
 ************************************************************
 *       Numerical Routines for derived quantities          *
 ************************************************************
 */
static compute_energy(dens, stag, op, size)
    float *dens, *stag, *op;
    int size;
{
    int i;
    /*$dir no_recurrence*/
    for (i = 0; i < size; i++) {
	if (dens[i] == 0.0)
	  op[i] = CFD_MAXFLOAT;
	else
	  op[i] = stag[i] / dens[i];
    }
}

static compute_mom_squared(xm, ym, zm, op, size)
    float *xm, *ym, *zm, *op;
    int size;
{
    int i;
    /* replication permits vector/parallel code generation */
	/*$dir no_recurrence*/
	for (i = 0; i < size; i++) {
	    op[i] = xm[i]*xm[i] + ym[i]*ym[i] + zm[i]*zm[i];
        }
}

static compute_press(dens, xmom, ymom, zmom, stag, op, size, gamma)
    float *dens, *xmom, *ymom, *zmom, *stag, *op;
    double gamma;
    int size;
{
    int i;
    compute_mom_squared(xmom, ymom, zmom, op, size);

    /*$dir no_recurrence*/
    for (i = 0; i < size; i++) {
	if (dens[i] == 0.0)
	  op[i] = CFD_MAXFLOAT;
	else
	  op[i] = (gamma - 1.0) * (stag[i] - 0.5 * op[i] / dens[i]);
    }
}

static compute_enthalpy(dens, xmom, ymom, zmom, stag, op, size, gamma)
    float *dens, *xmom, *ymom, *zmom, *stag, *op;
    double gamma;
    int size;
{
    int i;
    compute_press(dens, xmom, ymom, zmom, stag, op, size, gamma);

    /*$dir no_recurrence*/
    for (i = 0; i < size; i++) {
	if (dens[i] == 0.0)
	  op[i] = CFD_MAXFLOAT;
	else
	  op[i] =  (gamma / (gamma - 1.0)) * (op[i] / dens[i]);
    }
}

static compute_mach(dens, xmom, ymom, zmom, stag, op, size, gamma)
    float *dens, *xmom, *ymom, *zmom, *stag, *op;
    double gamma;
    int size;
{
    int i;
    compute_mom_squared(xmom, ymom, zmom, op, size);
    /*$dir no_recurrence*/
    for (i = 0; i < size; i++) {
	if (dens[i] == 0.0) {
	    op[i] = CFD_MAXFLOAT;
	} else {
	    float pressure = (gamma - 1.0) * (stag[i] - .5 * op[i] / dens[i]);
	    float mach1 = sqrt(gamma * pressure / dens[i]);
	    op[i] = sqrt(op[i]) / (dens[i] * mach1);
	}
    }
}    

static compute_temp(dens, xmom, ymom, zmom, stag, op, size, gamma, gas_constant)
    float *dens, *xmom, *ymom, *zmom, *stag, *op;
    double gamma, gas_constant;
    int size;
{
    int i;
    compute_mom_squared(xmom, ymom, zmom, op, size);
    /*$dir no_recurrence*/
    for (i = 0; i < size; i++) {
	if (dens[i] == 0.0) {
	    op[i] = CFD_MAXFLOAT;
	} else {
	    float pressure = (gamma - 1.0) * (stag[i] - 0.5 * op[i] / dens[i]);
	    op[i] =  pressure / (dens[i] * gas_constant);
	}
    }
}

static compute_tot_press(dens, xmom, ymom, zmom, stag, op, size, gamma)
    float *dens, *xmom, *ymom, *zmom, *stag, *op;
    double gamma;
    int size;
{
    int i;
    compute_mom_squared(xmom, ymom, zmom, op, size);
    /*$dir no_recurrence*/
    for (i = 0; i < size; i++) {
	if (dens[i] == 0.0) {
	    op[i] = CFD_MAXFLOAT;
	} else {
	    float pressure = (gamma - 1.0) * (stag[i] - .5 * op[i] / dens[i]);
	    float mach1_squared = gamma * pressure / dens[i];
	    float mach_squared = op[i] / (dens[i] * dens[i] * mach1_squared);
	    float x = 1.0 + .5 * (gamma - 1.0) * mach_squared;
	    op[i] = pressure * exp(log(x) * gamma / (gamma - 1.0));
	}
    }
}

static compute_tot_temp(density, xmom, ymom, zmom, stagnation, op, size, gamma, gas_constant)
    float *density, *xmom, *ymom, *zmom, *stagnation, *op;
    double gamma, gas_constant;
    int size;
{
    int i;
    compute_mom_squared(xmom, ymom, zmom, op, size);
    /*$dir no_recurrence*/
    for (i = 0; i < size; i++) {
	float dens = density[i];
	float stag = stagnation[i];
	if (dens == 0.0) {
	    op[i] = CFD_MAXFLOAT;
	} else {
	    float pressure = (gamma - 1.0) * (stag - .5 * op[i] / dens);
	    float mach1_squared = gamma * pressure / dens;
	    float mach_squared = op[i] / (dens * dens * mach1_squared);
	    float temperature =  pressure / (dens * gas_constant);
	    op[i] = temperature * (1.0 + .5 * (gamma - 1.0) * mach_squared);
	}
    }
}    

static scan_minmax_range ( out_data, nnodes, rmin, rmax , block )
		float *out_data, *rmin, *rmax;
		int   nnodes, block;   
{
		int i;

		if (block == 0)
			*rmin = *rmax = out_data[0];

		for( i = 0; i < nnodes; i++ ) {
			if (out_data[i] < *rmin)
				*rmin = out_data[i];
			if (out_data[i] > *rmax)
				*rmax = out_data[i];
		}
#ifdef DEBUG_PRINT
		printf("  range scan min= %f max= %f \n", *rmin, *rmax);
#endif
}
